# Generated by Django 4.0.4 on 2024-07-01 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_orderitem_unit_price'),
        ('store', '0006_alter_customer_options_alter_product_promotions_and_more'),
    ]

    operations = [
    ]
